### ISSUE TITLE
Button: "Reset the machine" is difficult to see.

### ISSUE THREAD

**Issue by dandelionadia** [Redd-Developer/redd.one#36]
## Motivation:

In the article: "Debounce vs Throttle: Definitive Visual Guide" content in the button: "Reset the machine" is difficult to see.

![1](https://user-images.githubusercontent.com/33199975/86219818-078ccf80-bb83-11ea-8dba-ab88c70152f6.png)

**Comment by kettanaito** [comment]
Thanks for spotting this! I'd be thankful for a pull request.
