### ISSUE TITLE
Request: Add RSS feed

### ISSUE THREAD

**Issue by SeanMcP** [Redd-Developer/redd.one#58]
I enjoyed [an article on the blog](https://redd.one/blog/the-dark-side-of-open-source) and wanted to subscribe. Consider adding an RSS feed so that others can get updates with their favorite reader.

**Comment by kettanaito** [comment]
Thanks, @SeanMcP! 

Sure, RSS would be great to have. Maybe I'll add it once I have time. You're also welcome to contribute if this is something that interests you. I'd appreciate your help.

**Comment by SeanMcP** [comment]
I guess that's the best way to say "I appreciate your articles" 😄

**Comment by kettanaito** [comment]
Thank you so much, @SeanMcP! The highest praise I can get.
